apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-example
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/pafable/kubernetes-apps.git
    targetRevision: HEAD
    path: jenkins
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
