---
- hosts: all
  become: true
  tasks:
  - name: install base packages
    package:
      name:
        - vim
        - tmux
        - htop
        - net-tools
      state: latest
      update_cache: yes
