---
- hosts: web_servers
  become: true
  tasks:
  - name: uninstall apache package
    package:
      name: "{{ apache_package }}"
      purge: true
      state: absent
      update_cache: true

  - name: uninstall default_site.html
    file:
      state: absent
      path: /var/www/html/index.html
