---
- hosts: all
  become: true
  tasks:
  - name: uninstall base packages
    package:
      name:
        - vim
        - tmux
        - htop
        - net-tools
        - unzip
      purge: true
      state: absent
      update_cache: yes

  - name: uninstall terraform 1.6.2
    file:
      state: absent
      path: /usr/local/bin/terraform
