apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: [ "on-demand" ]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: [ "t3.small", "t3.medium" ]
  limits:
    resources:
      cpu: 95
  provider:
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: "${ebs_volumeSize}"
        volumeType: "${ebs_volumeType}"
    subnetSelector:
      kubernetes.io/cluster: shared
    securityGroupSelector:
      karpenter.sh/discovery/"${cluster_id}": "${cluster_id}"
    tags:
      karpenter.sh/discovery/"${cluster_id}": "${cluster_id}"
  ttlSecondsAfterEmpty: 30
