name: Test job for custom actions runner
on:
  workflow_dispatch:

jobs:
  deploy-eks:
    runs-on: hydra
    steps:
      - uses: actions/checkout@v4

      - name: say hello
        run: |
          echo hello world!
