name: CI Tests
on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'
      - 'test/*'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11'

      - name: check python version
        run: python --version

      - name: configuring aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: 'us-east-1'

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.1
          terraform_wrapper: false

      - name: running tests
        run: make test
