name: Deploy Base Infra
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  deploy-base-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11'
          
      - name: configuring aws
        uses: aws-actions/configure-aws-credentials@v4
          
      - name: check python version
        run: python --version
      
      - name: install dependencies
        run: make install
     
      - name: deploy
        run: make deploy
